- hosts: localhost
  vars:
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
  - name: Update homebrew
    homebrew:
      update_homebrew: yes
    tags:
    - zsh
    - terminal
    - essentials
    - dotfiles
  tasks:
  - import_tasks: tasks/zsh.yml
  - import_tasks: tasks/dotfiles.yml
  - import_tasks: tasks/personal-projects.yml