- hosts: localhost
  vars:
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
  - name: Update homebrew
    when: ansible_distribution == 'MacOSX'
    homebrew:
      update_homebrew: yes
    tags:
    - essentials
    - extras
  tasks:
  - import_tasks: tasks/zsh.yml
    tags: zsh
  - import_tasks: tasks/dotfiles.yml
    tags: dotfiles
  - import_tasks: tasks/personal-projects.yml
  - import_tasks: tasks/packages.yml
  - import_tasks: tasks/fonts.yml
  - import_tasks: tasks/node.yml
