- name: Install essential packages from brew
  homebrew:
    name:
    - ansible
    - tmux
    - fzf
    - curl
    - httpie
    - coreutils
    - ripgrep
    - fd
    - rsync
    - direnv
    - git
    - openssh
    - ssh-copy-id
    - python
    - go
    state: present
  tags:
  - essentials
  - essentials-cli
- name: Install essential packages from brew cask
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop:
  - google-chrome
  - docker
  - alacritty
  ignore_errors: yes
  tags:
  - essentials
  - essentials-gui