- name: Install essential packages from brew
  homebrew:
    name:
    - ansible
    - tmux
    - fzf
    - curl
    - httpie
    - coreutils
    - ripgrep
    - fd
    - rsync
    - git
    - openssh
    - ssh-copy-id
    - python
    - go
    state: present
  tags:
  - essentials
- name: Install essential packages from brew cask
  homebrew_cask:
    name:
    - google-chrome
    - docker
    state: present
  tags:
  - essentials