- name: Installing GNU/stow
  ansible.builtin.package:
    name: stow
    state: present
  tags:
  - workflow-console
  - essentials
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: git@github.com:NikitaKurpas/dotfiles.git
    dest: ~/.dotfiles
    recursive: yes
    update: yes
    version: main
  tags:
  - workflow-console
  - essentials
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./install
  tags:
  - workflow-console
  - essentials
