- name: Tap extra brew repos
  homebrew_tap:
    name: beeftornado/rmtree
    state: present
  tags:
  - extras
- name: Install extra packages from brew
  homebrew:
    name:
    - ruby # upgrade ruby
    - htop
    - gnupg
    - git-lfs
    - rlwrap # required by cht.sh --shell
    - tldr
    - gh
    - brew-rmtree
    - mas
    state: present
  tags:
  - extras
- name: Install extra packages from brew cask
  homebrew_cask:
    name:
    - firefox
    - slack
    - setapp
    - 1password-cli
    - jetbrains-toolbox
    - visual-studio-code
    #- sloth # App that shows all open files and sockets
    - figma
    - toggl-track
    - qlstephen
    - quicklook-json
    #- postico # GUI client for PostgreSQL databases
    #- postman
    state: present
  tags:
  - extras
- name: Install extra packages with gem
  community.general.gem:
    name: colorls
    state: present
  tags:
  - extras