- name: Install node
  homebrew:
    name: node
    state: present
  tags:
  - essentials
- name: Clone nvm
  ansible.builtin.git:
    repo: git@github.com:nvm-sh/nvm.git
    dest: ~/.nvm
    update: yes
  tags:
  - essentials
- name: Checkout latest nvm
  shell: cd ~/.nvm && git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)`
  tags:
  - essentials
- name: Install LTS node
  shell: . ~/.nvm/nvm.sh && nvm install --lts
  tags:
  - essentials
- name: Install yarn
  homebrew:
    name: yarn
    state: present
  tags:
  - essentials
- name: Install fkill with npm
  npm:
    name: fkill-cli
    global: yes
  tags:
  - extras
- name: Install zx with npm
  npm:
    name: zx
    global: yes
  tags:
  - extras
