- name: Install node and yarn
  ansible.builtin.package:
    name: 
    - node
    - yarn
    state: present
  tags:
  - extras
  - workflow-node
- name: Install nvm
  block:
  - name: Clone nvm
    ansible.builtin.git:
      repo: git@github.com:nvm-sh/nvm.git
      dest: ~/.nvm
      update: yes    
  - name: Checkout latest nvm
    shell: cd ~/.nvm && git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)`
  tags:
    - extras
    - workflow-node
- name: Install LTS node
  shell: . ~/.nvm/nvm.sh && nvm install --lts
  tags:
  - extras
  - workflow-node
- name: Install stuff with npm
  npm:
    name: "{{ item }}"
    global: yes
  loop:
  - fkill-cli
  - zx
  tags:
  - extras