- name: Install packages for console workflow
  become: true
  ansible.builtin.package:
    name:
    - git
    - ansible
    - tmux
    - fzf
    - coreutils
    - less
    - ripgrep
    - fd
    - bat
    - curl
    - httpie
    - git-delta
    - rsync
    - direnv
    - openssh
    - ssh-copy-id
    state: present
  tags:
  - workflow-console
  - essentials
- name: Install packages for console workflow from brew cask
  when: ansible_distribution == 'MacOSX'
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop:
  - alacritty
  ignore_errors: true
  tags:
  - workflow-console
  - essentials
- name: Update terminfos
  when: ansible_distribution == 'MacOSX'
  block:
    - name: Create a term dir for terminfo files
      ansible.builtin.tempfile:
        state: directory
        suffix: build
      register: terminfo_tmp
    - name: Update tmux terminfo
      shell: curl -L https://gist.githubusercontent.com/nicm/ea9cf3c93f22e0246ec858122d9abea1/raw/37ae29fc86e88b48dbc8a674478ad3e7a009f357/tmux-256color > {{ terminfo_tmp.path }}/tmux-256color.info && tic -x {{ terminfo_tmp.path }}/tmux-256color.info # https://gist.github.com/nicm/ea9cf3c93f22e0246ec858122d9abea1
    - name: Update other terminfos
      shell: /usr/local/opt/ncurses/bin/infocmp {{ item }} > {{ terminfo_tmp.path }}/{{ item }}.info && tic -xe {{ item }} {{ terminfo_tmp.path}}/{{ item }}.info
      loop:
      - alacritty
      - alacritty-direct
  ignore_errors: true
  tags:
  - workflow-console
  - essentials

- name: Install other essential packages from 
  become: true
  ansible.builtin.package:
    name:
    - python
    - go
    state: present
  tags:
  - essentials

- name: Install other essentials packages from brew cask
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop:
  - google-chrome
  - docker
  ignore_errors: true
  tags:
  - essentials
  - essentials-gui
