- name: Install zsh
  homebrew:
    name: zsh
    state: present
  tags:
  - workflow-console
  - essentials
- name: Change shell to zsh
  shell: chsh -s `which zsh`
  tags:
  - workflow-console
  - essentials
- name: Check if oh my zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: oh_my_zsh
  tags:
  - workflow-console
  - essentials
- name: Install ohmyzsh
  when: oh_my_zsh.stat.exists == False
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
  - workflow-console
  - essentials
- name: Install Powerlevel10k
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
  tags:
  - workflow-console
  - essentials
- name: Install zsh plugin for autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  tags:
  - workflow-console
  - essentials
- name: Install zsh plugin for syntax highlighting
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  tags:
  - workflow-console
  - essentials
